version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upsi_skillhub_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: upsi_skillhub_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: student_data
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
